# Configuration for the APIM service broker

# Logging configuration
log:
  logFile: "server.log"
  logLevel: "debug"

# HTTP server configuration
http:
  # Basic Auth configuration for the service broker
  auth:
    username: "admin"
    password: "admin"

  # HTTPS configuration
  tls:
    enabled: false
    key: "key.pem"
    cert: "cert.pem"

  host: "0.0.0.0"
  port: 8444

apim:
  username: "admin"
  password: "admin"
  # If "true", doesn't validate the certificate for the APIM
  insecureCon: true
  tokenEndpoint: "https://localhost:8243"
  dynamicClientEndpoint: "https://localhost:9443"
  publisherEndpoint: "https://localhost:9443"
  storeEndpoint: "https://localhost:9443"

db:
  host:     "localhost"
  port:     3306
  username: "root"
  password: "root123"
  database: "broker"
  logMode:  false
