# Configuration for the APIM service broker

# Logging configuration
log:
  logFile: "server.log"
  logLevel: "debug"

# HTTP server configuration
http:
  # Basic Auth configuration for the service broker
  auth:
    username: "admin"
    password: "admin"

  # HTTPS configuration
  tls:
    enabled: false
    key: "key.pem"
    cert: "cert.pem"

  host: "0.0.0.0"
  port: 8443

planSchema: "./config/plan-schema.json"